# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('image_hash', models.CharField(max_length=128)),
                ('hours', models.CharField(max_length=256)),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KnownDentists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_id', models.IntegerField(default=0)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dentist.Dentists')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='knowndentists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dentist.Users'),
        ),
    ]
