# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_auto_20171122_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentists',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
