# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0003_auto_20171123_1136'),
    ]

    operations = [
    ]
