# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0004_auto_20171123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentists',
            name='image_hash',
            field=models.CharField(max_length=2000),
        ),
    ]
